fraud_mitigation_dwh:
  outputs:
    dev:
      dataset: fraud_mitigation
      fixed_retries: 1
      keyfile: /opt/airflow/credentials.json
      location: us
      method: service-account
      priority: interactive
      project: "extreme-display-392014"
      threads: 4
      timeout_seconds: 300
      type: bigquery
    prod:
      dataset: fraud_mitigation
      fixed_retries: 1
      keyfile: /opt/airflow/credentials.json
      location: us
      method: service-account
      priority: interactive
      project: "extreme-display-392014"
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev
